"""Описание изменений

Revision ID: 1101f367295e
Revises: 
Create Date: 2024-01-03 21:31:30.009322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1101f367295e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('total', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
