"""Добавил Логин и пользователей

Revision ID: 57eef98f62e8
Revises: ddfb7607788d
Create Date: 2024-01-09 19:34:49.251852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57eef98f62e8'
down_revision = 'ddfb7607788d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
