"""Описание изменений

Revision ID: ab7e763b8c3a
Revises: 1101f367295e
Create Date: 2024-01-03 21:49:10.759779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7e763b8c3a'
down_revision = '1101f367295e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'total')
    # ### end Alembic commands ###
